#!/usr/bin/env bash
#Configure domain zone so that the subdomain www points to your load-balancer IP
#shellcheck disable=SC2059
subdomain()
{
    RECORD_TYPE=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/{print $4}')
    DEST=$(dig "$1" | awk '/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/{print $5}')
    echo The subdomain "$2" is a "$RECORD_TYPE" record and points to "$DEST"
}

if [ "$2" ]
then
    subdomain "$2.$1" "$2"
else
    subdomain "www.$1" www
    subdomain "lb-01.$1" lb-01
    subdomain "web-01.$1" web-01
    subdomain "web-02.$1" web-02
fi
