#!/usr/bin/env bash
# Installs the nginx engine
sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
echo 'Hello World' > /var/www/html/index.nginx-debian.html
service nginx start
