#!/usr/bin/env bash
# This script configures an loadBalancer
sudo apt-get update
apt-get install -y haproxy=1.6.\*
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver 4495-web-01 3.227.0.151:80 check\n\tserver 4495-web-02 44.192.94.131:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
