#!/usr/bin/env bash
# This script configures an loadBalancer
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i '$ a\ \nfrontend http_front\n\t bind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 4495-web-01 3.227.0.151:80 check\n\tserver 4495-web-02 44.192.94.131:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
